revert arm64: flounder: change Vret to 600mV for ES part
The 550mV retention voltage setting in ES part is not
recommended, hence, adjusted to 600mV.

Bug 17265584

Change-Id: I003675281f55d3d82de3d3b4985fb939d7a9e6cc (reverted from commit e192f0b4938a7602c6e8b7ef842f95d8bbe8bf69)

undefined reference to `fuse_cp_rev_check'
to fix build on gcc5